apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prom
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: HEAD
    chart: kube-prometheus-stack