apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prom
  namespace: monitoring
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 57.0.3
    helm:
      releaseName: prom
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring